### ISSUE TITLE
dtmf

### ISSUE THREAD

**Issue by atulgo** [nimaltd/Sim800_V2#13]
Detection of DTMF tones in my SIM800L module.

I get "OK" when I send 'AT+DDET=1,1000,1,1* ' over uart .
But it doesnt seem to detect anything afterwards.
Perhaps I am doing something wrong.
Would be great to get some feedback.

regards
Atul
ref : *SIM800 Series_AT Command Manual_V1.09

**Comment by nimaltd** [comment]
hello. please update your module and try again. I don't have any module to test.

**Comment by atulgo** [comment]
my operator doesnt seem to support Dtmf properly.
Regards
