### ISSUE TITLE
Gsm_MsgSendText send message twice

### ISSUE THREAD

**Issue by aliyaghoobi88** [nimaltd/Sim800_V2#18]
hi @nimaltd 
thank you for your useful library 
when I send a message in the **Gsm_UserNewMsg** function with **Gsm_MsgSendText**    any message send twice 
I guess receive message doesn't delete in  **StartSim80xTask**

   for(uint8_t i=0 ;i<sizeof(Sim80x.Gsm.HaveNewMsg) ; i++)
    {
      if(Sim80x.Gsm.HaveNewMsg[i] > 0)
      {
        //Gsm_MsgGetMemoryStatus();        
        if(Gsm_MsgRead(Sim80x.Gsm.HaveNewMsg[i])==true)
        {
					osDelay(100);
          Gsm_UserNewMsg(Sim80x.Gsm.MsgNumber,Sim80x.Gsm.MsgDate,Sim80x.Gsm.MsgTime,Sim80x.Gsm.Msg);
					osDelay(100);
        **Gsm_MsgDelete(Sim80x.Gsm.HaveNewMsg[i]);**  /*message not deleted in this line*/
					osDelay(100);
        }
        Gsm_MsgGetMemoryStatus();  
        Sim80x.Gsm.HaveNewMsg[i]=0;
      }        
    }    
    //###########################################
    if(Sim80x.Gsm.MsgUsed > 0)
    {   
      if(Gsm_MsgRead(UnreadMsgCounter)==true)
      {
        Gsm_UserNewMsg(Sim80x.Gsm.MsgNumber,Sim80x.Gsm.MsgDate,Sim80x.Gsm.MsgTime,Sim80x.Gsm.Msg);
        **Gsm_MsgDelete(UnreadMsgCounter);**  /*message delete in this line*/
        Gsm_MsgGetMemoryStatus();
      }
      UnreadMsgCounter++;
      if(UnreadMsgCounter==150)
        UnreadMsgCounter=0;      
    }

**Comment by nimaltd** [comment]
Hi. Please use my last library. Http://github.com/nimaltd/gsm

**Comment by aliyaghoobi88** [comment]
Thank you @nimaltd
