### ISSUE TITLE
Please clarify this Regex

### ISSUE THREAD

**Issue by danyhm** [nimaltd/Sim800_V2#2]
https://github.com/nimaltd/Sim800_V2/blob/5c76a909f7f69a1f3bea00b078e56c0fb0795abc/Sim80x.c#L734

Can you please provide a reference for that Regex? 
I'm using Quectel which has exactly the same format for this command and it gets the number right but the date appears as 2017/05/ so I guess that's where the rest gets messed up and I don't get the msgOk flag because tmp_int32_t equals 2.

**Comment by nimaltd** [comment]
I don't have quectel module. 
maybe quectel module format is a bit different.

**Comment by nimaltd** [comment]
please see answer on debug

**Comment by danyhm** [comment]
i found the bug , the format is different
