### ISSUE TITLE
Sim80x

### ISSUE THREAD

**Issue by AndreaCorpino** [nimaltd/Sim800_V2#4]
Hi, your guide is very good. I found it well done and interesting. 
One Question:
When you say _7) call Sim80x_Init(osPriorityLow) on your app. _ , where in the "main" i should put it to test your project?

Thanks and nice day.

**Comment by nimaltd** [comment]
please Open FreeRtos.c and call Sim80x_Init(osPriorityLow) in first of initial task 

/* StartDefaultTask function */
void StartDefaultTask(void const * argument)
{
    Sim80x_Init(osPriorityLow) ;
  .. 
... 
...

**Comment by AndreaCorpino** [comment]
Thank you!
