### ISSUE TITLE
problem in FreeRTOS function in SIM800_V2

### ISSUE THREAD

**Issue by mbta009** [nimaltd/Sim800_V2#5]
Hello and respect
If possible, share some code samples for sim800_V2. I have little experience with FreeRTOS and newbie in STM32. By the command that you said the library file was added to the code. After the program and code testing, the osKernelStart function hangs. I am a Persian user, is it possible to subscribe to another social network ID for share my code for you?  part of code was important that commented under text. 
use STM32F103RBT6 
//**************************
Sim80x_Init(osPriorityLow);
MX_FREERTOS_Init();
osKernelStart();  // hang up on this function 
//*************************
Thank you, Barati
mahdi2barati@gmail.com

**Comment by danyhm** [comment]
this is GitHub if you have an issue you should post your code here.
my guess is that your freeRTOS heap size is not enough. try increasing your heap size.

also when the kernel starts it doesn't get past that function and the defined tasks start to get executed.

**Comment by mbta009** [comment]
@danyhm OK. This link is my code ( main.c in Src ). Thank you for checking that. my Stm32cubemx file Also attached. FreeRTOs heap size is 3072 B 
Thanks @danyhm

**Comment by danyhm** [comment]
@mbta009 
I took a look at your code and it's wrong. you need to call sim80x_init() in your app (a freertos task).
i suggest reading more about RTOS and how to work with it, there're a lot of resources and examples online

**Comment by nimaltd** [comment]
Hello guys. your heap size is too low. 
And add init function in a task.

**Comment by nimaltd** [comment]
I think minimum must be 8192 bytes.
and Please read more about FreeRTOS :)

**Comment by yuriy23** [comment]
Good day. there are problems too. Could you set an example freertos + keil? I would be very grateful. trying to run gprs with tcp / ip
Thank!

**Comment by PrabhuNatarajanN** [comment]
![GSM_V2](https://user-images.githubusercontent.com/50335539/57242119-4cd17200-7050-11e9-87bc-beff734fbd70.jpg)
 I am getting following error GSM_v2 library. 

Could you please share the fix this issue

**Comment by nimaltd** [comment]
Helli. Whst is your module. You simcsrd is ok?  This library work fine.  I dont know why you have that problemOn May 6, 2019 9:43 PM, PrabhuNatarajanN <notifications@github.com> wrote:
I am getting following error GSM_v2 library.
Could you please share the fix this issue

**Comment by PrabhuNatarajanN** [comment]
Dear Nimaltd,

I am tested sim800 V1 working fine. i try to use version memory initialize
error came and  not able to read.

SIM900 A6 module.

Thanks
Prabhu Natarajan

‪On Tue, May 7, 2019 at 12:13 AM ‫Nima Askari ----- نیما عسکری‬‎ <
notifications@github.com> wrote:‬

> Helli. Whst is your module. You simcsrd is ok?  This library work fine.  I
> dont know why you have that problemOn May 6, 2019 9:43 PM, PrabhuNatarajanN

**Comment by nimaltd** [comment]
Its work with sim800On May 7, 2019 9:03 AM, PrabhuNatarajanN <notifications@github.com> wrote:Dear Nimaltd,



I am tested sim800 V1 working fine. i try to use version memory initialize

error came and  not able to read.



SIM900 A6 module.



Thanks

Prabhu Natarajan



‪On Tue, May 7, 2019 at 12:13 AM ‫Nima Askari ----- نیما عسکری‬‎ <

notifications@github.com> wrote:‬



> Helli. Whst is your module. You simcsrd is ok?  This library work fine.  I

> dont know why you have that problemOn May 6, 2019 9:43 PM, PrabhuNatarajanN

**Comment by PrabhuNatarajanN** [comment]
Dear Nimaltd,

Thanks for fast reply.

Regards
Prabhu Natarajan

‪On Tue, May 7, 2019 at 10:33 AM ‫Nima Askari ----- نیما عسکری‬‎ <
notifications@github.com> wrote:‬

> Its work with sim800On May 7, 2019 9:03 AM, PrabhuNatarajanN <
> notifications@github.com> wrote:Dear Nimaltd,
>
> I am tested sim800 V1 working fine. i try to use version memory initialize
> error came and not able to read.
>
> SIM900 A6 module.
>
> Thanks
> Prabhu Natarajan
>
> ‪On Tue, May 7, 2019 at 12:13 AM ‫Nima Askari ----- نیما عسکری‬‎ <
> notifications@github.com> wrote:‬
>
> > Helli. Whst is your module. You simcsrd is ok? This library work fine. I
> > dont know why you have that problemOn May 6, 2019 9:43 PM,
> PrabhuNatarajanN

**Comment by PrabhuNatarajanN** [comment]
shall we can use this library GPRS with MQTT application?

**Comment by nimaltd** [comment]
NopOn May 7, 2019 11:43 AM, PrabhuNatarajanN <notifications@github.com> wrote:shall we can use this library GPRS with MQTT application?
