### ISSUE TITLE
Bug in function `bool Gsm_Ussd(char *send, char *receive)`

### ISSUE THREAD

**Issue by d-serj** [nimaltd/Sim800_V2#6]
Hello! Could you descrive (write comments) of the API functions in your code? 

In my case, I dont understand the meaning of the parameter `receive` in function  `bool  Gsm_Ussd(char *send, char *receive)` . I think, there is no effect of code in this function `if(receive != NULL) receive = Sim80x.Gsm.Msg;` because `receive` is local variable. Or I need to pass pointer to pointer as the parameter?

P.S. Sorry for my English.

**Comment by nimaltd** [comment]
Hello. Call init in your task. 
Reseive can a global variable. 
Like 
Char myussdanswer[128];
Or null.
If it's null. You can read answer in sim80x structure ( in sim80x.gsm.msg)

**Comment by d-serj** [comment]
My solution is to use `memcpy(receive, Sim80x.Gsm.Msg, receiveSize);` instead of 'receive = Sim80x.Gsm.Msg` or pass pointer to pointer as function argument.

**Comment by nimaltd** [comment]
I dont have a board for test now.
 . I try it soon. Thank you for report bugs
